stack = []

stack.append(5)
stack.append(3)
print(stack.pop())
stack.append(2)
stack.append(8)
print(stack.pop())
print(stack.pop())
stack.append(9)
stack.append(1)
print(stack.pop())
stack.append(7)
stack.append(6)
print(stack.pop())
print(stack.pop())
stack.append(4)
print(stack.pop())
print(stack.pop())
